[oauth]
username = "javiera"
password = "Namibia"


[gsheets]
type = "service_account"
project_id = "codificator3000"
private_key_id = "3367fec8e89f3b51427130b013f3ba7827604178"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC1Z9w66ZeJ+/WW
9Pry/yIIKY0kIAZvyaLGVepiC27ppgC3JR2znJKDQnDgCLz4XuGeEv8npT7SOJQS
eNLCzGQ55cqQzI1Jk6iJD9dqIZJMYO6EGRFb07PiVjbn8rsjstiv21eBfMBK2N6g
hx5ZD9cwJ+bFezHZuIgSNGQWglYYmW976rg7QMuL9HxvHAND4jhLTik+wei4UyTH
C4je4sKyZMumFtg7vJhD2j0LzmcJ6o/J5SBO5pT07MgrpCw+ON8aEVgOyikBipPe
2g7FESE4GjCi317S46hfwG5mUsBGVqA8z/oT+pou5bVyu4FixSbtaYRI7I39Y3Pp
rXedqzHVAgMBAAECggEAAKd3j4LTeBI/iCQpWiz6BhuC6x7Dxy1r99khd5Rg+a4O
ke/WqT98S8WL5f2XaNyMEGeId1p3h9yKXtKut+MdeBP7D1tIJdFxfyUJJX8qKY+u
ly1b9v/OxeyCVYMg56JieP01Kz4Jl3uBZK94DYwqvigMA1RMEWPtTFuCAjlwGWCa
twI/JwP/mm7o+SyvEpDELsi9sCAEImZOlYW58dy0qMnNV6A2Z+nEEnOCxu3HhSDw
CtpgMkt21GNfbYsyb60YNRpWTNe8s9PTlnJCS1beDicO9oZjhCCPwMhzh5qaSxm7
lOZlJMW+BcpZ5ggjKrUJU6aeGYFeKoXN7fA+EU51tQKBgQDhnXtaej0+w/kcZ2ms
LqNY9C/SZO4WlZDeDOAfgpumx6muztfnWGH+vHG3L8JNDG+NMJt1xBK7fB0tuytB
vMVCCZu8EyyMF1eBIqJQGW2phB7ufzaxlNVwI1DJ65oGB6eG5HoKNn73H7fPRNC/
4yE2o3+guACQ+zYkeKFOMtU3uwKBgQDN1iwIQcDNqua29O5fHhX7oTiMEtYRO+q7
5j7DtpAz70k7yl5R4VzIO6yEqUFqP2wFWl6OA26dVTTnE7jY81YhuZLH1r72kj9C
0sU0dDgpsJvPaJqM6MIpx/MYUtw5TXWr+h8BvL+9kAnEi8G9VYkuu1m6/i5rnXhI
3BmD0BY7rwKBgEiCu611kg+FHqARYHYVOyyQtnnxNFAP29Jx4updqLbufsuO8PcK
gdxEJmwQrmri70s6bwxnavnUxu/2ss1a5S73NZU5uFyB9/6p6e7CbWtI6kQOoL5s
LjjvMLzkusjrVt1UuyBjKWU1TXcRD+JMFlWgMJmv6YavJlSMbJNcZQiXAoGAGSkj
6sJ22e0ZFKYt+SyJTV/wtJac2jBzyhIj+/J2ABMw5YEgNGwS1lsNBI5X86/a+XCJ
fFyJCexfchukDcj471hqy8jBQQyxdO6ksnu+XcI72YeU1MKi8U6CtadzSgHg72u8
nI7A9WAFAaR/wzAQe8jk+AmYDQmLqYRWDhnCjfsCgYAzT6dZXMQtsw2gkEexJhWK
iyI1ej74uKagHP2pjLRIOX4BAFU01NlXSUa3tYoNU/e02ODpvoB77aU2zHEhr+FV
JAU6nVH4sSCAlsc7yCSx6EsVWPsfJQWxJmo/8HjpkEKKZooOV9Ias5UTwS2ehXtb
CMcm2JtQh/gFCpTU36Hekw==
-----END PRIVATE KEY-----"""
client_email = "codificator3000@codificator3000.iam.gserviceaccount.com"
client_id = "100280438071955403306"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/codificator3000%40codificator3000.iam.gserviceaccount.com"
